# Generated by Django 4.2 on 2026-03-05 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='iin',
        ),
    ]
