# Generated by Django 4.2 on 2026-03-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_teacherapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherapplication',
            name='cv_text',
            field=models.TextField(blank=True, verbose_name='Опыт работы'),
        ),
        migrations.AddField(
            model_name='teacherapplication',
            name='portfolio_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на портфолио'),
        ),
    ]
