# Generated by Django 4.2 on 2026-02-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lessonprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'verbose_name': 'Прогресс урока', 'verbose_name_plural': 'Прогресс уроков'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('text', 'Текст/Видео'), ('simulation_chat', 'Симуляция: Чат (WhatsApp/Telegram)'), ('simulation_email', 'Симуляция: Email (Фишинг)')], default='text', max_length=20, verbose_name='Тип урока'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='scenario_data',
            field=models.JSONField(blank=True, help_text='Заполняется только для типов simulation_*', null=True, verbose_name='Сценарий симуляции (JSON)'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='score_earned',
            field=models.IntegerField(default=0, verbose_name='Полученные очки (XP)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст урока'),
        ),
    ]
