# Generated by Django 4.2 on 2026-02-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lessonprogress_options_lesson_lesson_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover_image',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на обложку'),
        ),
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание (визитка)'),
        ),
    ]
