# Generated by Django 4.2 on 2026-02-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_cover_image_course_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Пройден'),
        ),
    ]
