# Generated by Django 4.2 on 2026-02-19 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0006_lessonprogress_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок шага (необязательно)')),
                ('step_type', models.CharField(choices=[('text', 'Теория (Текст)'), ('video_url', 'Видео (YouTube/Ссылка)'), ('video_file', 'Локальное видео (Загрузка файла)'), ('simulation_chat', 'Симуляция: Чат (WhatsApp/Telegram)'), ('simulation_email', 'Симуляция: Email (Фишинг)'), ('quiz', 'Тест/Опрос')], default='text', max_length=20, verbose_name='Тип шага')),
                ('content', models.TextField(blank=True, verbose_name='Текст/Ссылка')),
                ('file', models.FileField(blank=True, null=True, upload_to='lesson_files/', verbose_name='Файл (Видео/Документ)')),
                ('scenario_data', models.JSONField(blank=True, help_text='Заполняется только для симуляций', null=True, verbose_name='Сценарий симуляции (JSON)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок шага')),
            ],
            options={
                'verbose_name': 'Шаг урока',
                'verbose_name_plural': 'Шаги уроков',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StepProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Пройден')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('score_earned', models.IntegerField(default=0, verbose_name='Полученные очки (XP)')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lessonstep')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прогресс шага',
                'verbose_name_plural': 'Прогресс шагов',
                'unique_together': {('student', 'step')},
            },
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='content',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_type',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='scenario_data',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.DeleteModel(
            name='LessonProgress',
        ),
        migrations.AddField(
            model_name='lessonstep',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='courses.lesson', verbose_name='Урок'),
        ),
    ]
