# Generated by Django 4.2 on 2026-03-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_lessonstep_stepprogress_remove_lesson_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonstep',
            name='step_type',
            field=models.CharField(choices=[('text', 'Теория (Текст + Markdown + Код)'), ('video_url', 'Видео (YouTube/Ссылка)'), ('video_file', 'Локальное видео (Загрузка файла)'), ('simulation_chat', 'Симуляция: Чат (WhatsApp/Telegram)'), ('simulation_email', 'Симуляция: Email (Фишинг)'), ('quiz', 'Тест/Опрос'), ('interactive_code', 'Тренажер кода (Написание скрипта)'), ('terminal', 'Эмулятор терминала (Linux/Хак)')], default='text', max_length=20, verbose_name='Тип шага'),
        ),
    ]
