# Generated by Django 4.2 on 2026-03-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик (Видит только автор)'), ('review', 'На модерации (Проверяется админом)'), ('published', 'Опубликован (Видят все студенты)'), ('rejected', 'Отклонен (Нужны правки)')], default='draft', max_length=20, verbose_name='Статус модерации'),
        ),
    ]
