# Generated by Django 4.2 on 2026-04-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_kk',
            field=models.CharField(max_length=200, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название категории'),
        ),
    ]
