# Generated by Django 4.2 on 2026-04-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_category_description_en_category_description_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='description_kk',
            field=models.TextField(null=True, verbose_name='Описание курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='short_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание (визитка)'),
        ),
        migrations.AddField(
            model_name='course',
            name='short_description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание (визитка)'),
        ),
        migrations.AddField(
            model_name='course',
            name='short_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание (визитка)'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название курса'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название урока'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название урока'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название урока'),
        ),
    ]
