# Generated by Django 4.2 on 2026-04-17 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_course_description_en_course_description_kk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_kk',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_kk',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description_kk',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='course',
            name='short_description_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='short_description_kk',
        ),
        migrations.RemoveField(
            model_name='course',
            name='short_description_ru',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title_kk',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='title_kk',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='title_ru',
        ),
    ]
