# Generated by Django 4.2 on 2026-04-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_remove_category_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('company', models.CharField(max_length=255, verbose_name='Компания')),
                ('email', models.EmailField(max_length=254, verbose_name='Рабочий Email')),
                ('employees', models.CharField(max_length=50, verbose_name='Штат сотрудников')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('contacted', 'Связались'), ('closed', 'Закрыта')], default='new', max_length=20, verbose_name='Статус')),
            ],
        ),
    ]
