# Generated by Django 4.2 on 2026-04-30 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_b2blead'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='b2blead',
            options={'verbose_name': 'B2B Заявка', 'verbose_name_plural': 'B2B Заявки'},
        ),
        migrations.AddField(
            model_name='b2blead',
            name='target_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b2b_leads', to='courses.course', verbose_name='Целевой курс'),
        ),
    ]
