# Generated by Django 4.2 on 2026-04-30 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_b2blead_options_b2blead_target_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Инвайт-код')),
                ('max_uses', models.PositiveIntegerField(default=50, verbose_name='Лимит использований')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Использовано раз')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='courses.course', verbose_name='Целевой курс')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites', to='courses.b2blead', verbose_name='B2B Заявка')),
            ],
            options={
                'verbose_name': 'Инвайт-код',
                'verbose_name_plural': 'Инвайт-коды',
            },
        ),
    ]
