# Generated by Django 4.2 on 2026-04-30 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0018_corporateinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateinvite',
            name='activated_by',
            field=models.ManyToManyField(blank=True, related_name='corporate_invites', to=settings.AUTH_USER_MODEL, verbose_name='Активировали код'),
        ),
    ]
