# Generated by Django 4.2 on 2026-05-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_corporateinvite_activated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2blead',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('contacted', 'Связались'), ('closed', 'Закрыта'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
