# Generated by Django 4.2 on 2026-06-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_alter_b2blead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик (Видит только автор)'), ('review', 'На модерации (Проверяется админом)'), ('published', 'Опубликован (Видят все студенты)'), ('rejected', 'Отклонен (Нужны правки)'), ('archived', 'В архиве (Скрыт из каталога)')], default='draft', max_length=20, verbose_name='Статус модерации'),
        ),
    ]
