# Generated by Django 4.2 on 2026-03-19 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0003_alter_quiz_lesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0010_course_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_type', models.CharField(choices=[('chat', 'Чат-симуляция'), ('email', 'Фишинговое письмо')], max_length=10, verbose_name='Тип сценария')),
                ('scenario_topic', models.CharField(blank=True, max_length=255, verbose_name='Тема сценария')),
                ('result', models.CharField(choices=[('passed', 'Пройден'), ('failed', 'Провален'), ('incomplete', 'Не завершён')], default='incomplete', max_length=15, verbose_name='Результат')),
                ('total_steps', models.PositiveIntegerField(default=0, verbose_name='Всего шагов')),
                ('correct_steps', models.PositiveIntegerField(default=0, verbose_name='Правильных шагов')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='Время (сек)')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_attempts', to='courses.lessonstep', verbose_name='Шаг урока')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Попытка сценария',
                'verbose_name_plural': 'Попытки сценариев',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioStepResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_index', models.PositiveIntegerField(verbose_name='Индекс шага')),
                ('message_text', models.TextField(blank=True, verbose_name='Сообщение сценария')),
                ('chosen_option_text', models.TextField(verbose_name='Выбранный вариант')),
                ('is_correct', models.BooleanField(verbose_name='Правильный выбор?')),
                ('feedback_shown', models.TextField(blank=True, verbose_name='Показанный фидбек')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_results', to='analytics.scenarioattempt', verbose_name='Попытка')),
            ],
            options={
                'verbose_name': 'Результат шага сценария',
                'verbose_name_plural': 'Результаты шагов сценариев',
                'ordering': ['step_index'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttemptDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='Итоговый балл (%)')),
                ('total_questions', models.PositiveIntegerField(verbose_name='Всего вопросов')),
                ('correct_answers', models.PositiveIntegerField(verbose_name='Правильных ответов')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='Время прохождения (сек)')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Завершение')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_details', to='quizzes.quiz', verbose_name='Квиз')),
                ('result', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail', to='quizzes.result', verbose_name='Результат (legacy)')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempt_details', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Детальная попытка квиза',
                'verbose_name_plural': 'Детальные попытки квизов',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(verbose_name='Правильно?')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='analytics.quizattemptdetail', verbose_name='Попытка')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='quizzes.question', verbose_name='Вопрос')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.choice', verbose_name='Выбранный ответ')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
